name: Template_iOSUIKit_VIPER
# configs:
#     Debug: debug
#     Release: release
# configFiles:
#   Debug: configs/Debug.xcconfig
#   Release: configs/Release.xcconfig
options:
  bundleIdPrefix: com.sakiyamaK
  deploymentTarget:
    iOS: 12.0
packages:
  IQKeyboardManagerSwift:
      url: https://github.com/hackiftekhar/IQKeyboardManager
      from: 6.5.0
  SnapKit:
      url: https://github.com/SnapKit/SnapKit
      from: 5.0.1
  # Lottie:
  #     url: https://github.com/airbnb/lottie-ios
  #     from: 3.1.8
  Nimble:
      url: https://github.com/Quick/Nimble
      from: 9.0.0
  Quick:
      url: https://github.com/Quick/Quick
      from: 3.0.0
configs:
  Debug: debug
  Release: release
schemes:
  Template_iOSUIKit_VIPER:
    build:
      targets:
        Template_iOSUIKit_VIPER: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - Template_iOSUIKit_VIPER
      targets:
        - name: Template_iOSUIKit_VIPERTests
          # parallelizable: true
          randomExecutionOrder: true
        - name: Template_iOSUIKit_VIPERUITests
        #   # parallelizable: true
          randomExecutionOrder: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release

targets:
  Template_iOSUIKit_VIPER:
    platform: iOS
    type: application
    dependencies:
        - package: IQKeyboardManagerSwift
        - package: SnapKit
        # - package: Lottie
    sources:
      - path: Template_iOSUIKit_VIPER/
      - path: R.generated.swift
        optional: true
    # configFiles:
    #     Debug: configs/Debug.xcconfig
    #     Release: configs/Release.xcconfig
    preBuildScripts:
        - path: /bin/sh
          name: Run Script(R.swift)
          script: |
                "$PODS_ROOT/R.swift/rswift" generate "$SRCROOT/R.generated.swift"
          inputFiles:
                - $TEMP_DIR/rswift-lastrun
          outputFiles:
                - $SRCROOT/R.generated.swift
    scheme:
        testTargets:
            - Template_iOSUIKit_VIPERTests
            - Template_iOSUIKit_VIPERUITests

  # Unit Test
  Template_iOSUIKit_VIPERTests:
    platform: iOS
    type: bundle.unit-test
    sources: Template_iOSUIKit_VIPERTests
    dependencies:
      - package: Nimble
      - package: Quick
      - target: Template_iOSUIKit_VIPER

  # UI Test
  Template_iOSUIKit_VIPERUITests:
    platform: iOS
    type: bundle.unit-test
    sources: Template_iOSUIKit_VIPERUITests
    dependencies:
      - package: Nimble
      - package: Quick
      - target: Template_iOSUIKit_VIPER
    settings:
      TEST_TARGET_NAME: Template_iOSUIKit_VIPER
      INFOPLIST_FILE: Template_iOSUIKit_VIPERUITests/Info.plist